project:
  type: website
  output-dir: docs

website:
  title: "Intro to data exercises"
  body-header: "Exercises developed by Jen Buckley"
  sidebar:
    style: "docked"
    search: true
    contents:
      - href: index.qmd
        text: Start
      - href: Exercise-1.qmd
        text: Exercise 1 - SPSS environment
      - href: Exercise-2.qmd
        text: Exercise 2 - Examining variables
      - href: Exercise-3.qmd
        text: Exercise 3 - Relationships between variables
      - href: Exercise-4.qmd
        text: Exercise 4 - Chi-square and t-test
      - href: Exercise-5.qmd
        text: Exercise 5 - Regression 
      
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true


editor: visual

